### ISSUE TITLE
It seems does not work?

### ISSUE THREAD

**Issue by zzswang** [fansenze/snowpack-plugin-less#8]
Try to use this plugin following the readme.

install package into dev

```
yarn add --dev snowpack-plugin-less
```

update snowpack.config.js

```
  plugins: [
    "@snowpack/plugin-dotenv",
    "snowpack-plugin-less",
    "@snowpack/plugin-react-refresh",
  ],
```

include less file in app.tsx

```
import "antd/dist/antd.less";
```

But no styles comes in.

**Comment by fansenze** [comment]
it's bug of `snowpack` that i think.
because the plugin cannot received the `load` event for `.less`(which from `node_modules`) while i debug `snowpack-plugin-less`.

so without the `load` event for `.less`(which from `node_modules`), plugin cannot do anything.
.

**Comment by fansenze** [comment]
i suggest u try import `antd/dist/antd.less` in `.less`(not `node_modules`) not `.js`, then u import your `less` in `js`

```less
// app.less
@import "antd/dist/antd.less";

.app {
  // ...
};
```
```javascript
// app.js
import './app.less';
// ...
```

also u need to set `javascriptEnabled: true` to `snowpack-plugin-less`, because `antd.less` use js in less.
```js
// snowpack.config.js
module.exports ={
  // ...
  "plugins": [
    ["snowpack-plugin-less", {
      javascriptEnabled: true, // here
    }]
  ]
}
```

**Comment by zzswang** [comment]
Great it works, thanks @fansenze 

One step more, is it possible to dynamic loading less based on which component imported from antd?

**Comment by fansenze** [comment]
1. dynamic loading is JS syntax or framework syntax(webpack dynamic imports)
2. i think the less plugin is only use to process `.less` to `css` for web standards

**Comment by zzswang** [comment]
Ok, I get it now, thanks！
