### ISSUE TITLE
Unable to process less files

### ISSUE THREAD

**Issue by abdelrazzaq-dev** [fansenze/snowpack-plugin-less#9]
I got this when I use Antd Pro Component React Library
[esinstall:@ant-design/pro-card] Failed to load ../es/components/CheckCard/index.less
  Unexpected character '@'
do you think is a bug in the bulging or the library itself?

**Comment by fansenze** [comment]
`snowpack-plugin-less` use `less.render` to compile `.less`.
may be u should try to npm update `less`, then if also compile failed, u can report issue to `@ant-design/pro-card`
